--- #YAML:1.0
name:                WebService-YQL
version:             0.02
abstract:            Simple interface for Yahoo Query Language
license:             ~
author:              
    - Viorel Stirbu (cpan@stirbu.name)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    JSON::Any:                     
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
